monitor:
  url: https://herkul.app/ortak-kuran
  threshold: 10
  skip-bucket: 400 # skip next run if more pages than this exist
  start-time: "06:00"
  end-time: "23:50"
  interval: 1h
  fast-check:
    min-pages: 10
    max-pages: 100
    interval: 10m
playwright:
  headless: true
notification:
  to: ${MAIL_USERNAME}
mail:
  enabled: true
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    debug: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true